import type { MenuCategory } from "@/lib/types";

/**
 * Menú de ejemplo para previsualizar el storefront antes de conectar Supabase.
 * Refleja supabase/seed.sql. Los IDs son fijos para que el carrito funcione.
 */
export const SAMPLE_MENU: MenuCategory[] = [
  {
    id: "cat-burgers",
    name: "Hamburguesas",
    sort_order: 1,
    active: true,
    created_at: "",
    products: [
      {
        id: "prod-clasica",
        category_id: "cat-burgers",
        name: "Hamburguesa Clásica",
        description: "Carne de res, lechuga, tomate, queso",
        price: 75,
        image_url: null,
        available: true,
        track_stock: false,
        stock: 0,
        sort_order: 1,
        created_at: "",
      },
      {
        id: "prod-doble",
        category_id: "cat-burgers",
        name: "Hamburguesa Doble",
        description: "Doble carne, doble queso, tocino",
        price: 110,
        image_url: null,
        available: true,
        track_stock: false,
        stock: 0,
        sort_order: 2,
        created_at: "",
      },
    ],
  },
  {
    id: "cat-hotdogs",
    name: "Hot Dogs",
    sort_order: 2,
    active: true,
    created_at: "",
    products: [
      {
        id: "prod-hd-sencillo",
        category_id: "cat-hotdogs",
        name: "Hot Dog Sencillo",
        description: "Salchicha, mostaza, catsup",
        price: 45,
        image_url: null,
        available: true,
        track_stock: false,
        stock: 0,
        sort_order: 1,
        created_at: "",
      },
      {
        id: "prod-hd-especial",
        category_id: "cat-hotdogs",
        name: "Hot Dog Especial",
        description: "Salchicha, tocino, queso, jalapeños",
        price: 65,
        image_url: null,
        available: true,
        track_stock: false,
        stock: 0,
        sort_order: 2,
        created_at: "",
      },
    ],
  },
  {
    id: "cat-bebidas",
    name: "Bebidas",
    sort_order: 3,
    active: true,
    created_at: "",
    products: [
      {
        id: "prod-refresco",
        category_id: "cat-bebidas",
        name: "Refresco 600ml",
        description: "Coca-Cola, Sprite o Fanta",
        price: 25,
        image_url: null,
        available: true,
        track_stock: false,
        stock: 0,
        sort_order: 1,
        created_at: "",
      },
      {
        id: "prod-agua",
        category_id: "cat-bebidas",
        name: "Agua embotellada",
        description: "600ml",
        price: 18,
        image_url: null,
        available: true,
        track_stock: false,
        stock: 0,
        sort_order: 2,
        created_at: "",
      },
    ],
  },
];
